### ISSUE TITLE
Redirect error leads to nonworking service

### ISSUE THREAD

**Issue by marcows** [harry-wood/osm-notes-kml#10]
I already noticed it a few weeks ago.
https://harrywood.co.uk/maps/notes/kml/
gives ERR_TOO_MANY_REDIRECTS.

**Comment by harry-wood** [comment]
Thanks for noticing! I think I've fixed it.

I imagine it's been broken since May 20th when I [moved my domain to Cloudflare](https://twitter.com/harry_wood/status/1660008211628400641). I put a `.htaccess` file rule on this directory for forcing httpS. Not sure why that stopped working with a circular redirect. For now I've just removed it.

**Comment by marcows** [comment]
Yes, I think I have experienced it a few days before June. Thought it could be a temporary server problem or something which you were already aware of, so I didn't report it immediately.

Thanks for fixing!
